# Generated by Django 4.2.4 on 2023-10-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=50, null=True)),
                ('descriptions', models.TextField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Хедер',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/product', verbose_name='Фотография')),
                ('NameProduct', models.CharField(max_length=15, verbose_name='Название товара')),
            ],
            options={
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='SiteIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/icons/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('slide_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=450, null=True)),
                ('description', models.TextField(blank=True, max_length=450, null=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='api.slide')),
            ],
            options={
                'verbose_name_plural': 'Текст',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/images')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.slide')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='IconMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.URLField(null=True)),
                ('page_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_slide', to='api.header')),
            ],
            options={
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.AddField(
            model_name='header',
            name='icons',
            field=models.ManyToManyField(blank=True, related_name='header_icons', to='api.siteicon'),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=50, null=True)),
                ('user_agreement', models.FileField(blank=True, null=True, upload_to='user_agreements/')),
                ('company_description', models.TextField(max_length=250, null=True)),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('icons', models.ManyToManyField(blank=True, related_name='footer_icons', to='api.siteicon')),
            ],
            options={
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=450, null=True)),
                ('description', models.TextField(blank=True, max_length=450, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/images')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_blocks', to='api.slide')),
            ],
            options={
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
